### PR TITLE
add several podspec for CocoaPods support

### PR DESCRIPTION
**Pull request by banxi1988**
it's make me feel sad that I can't use this library directly in my iOS App with swiftpm,
so I have create several podspec files, make it's easy to use this lib in their CocoaPods project.

### CODE REVIEW

**Comment by LoganWright** [comment]
@banxi1988 after we tag 2.0 we're going to go back and start releasing cocoapods for some of these libs, we'll be revisiting this soon, thanks for adding it!

**Comment by EricYellow** [comment]
any update?

**Comment by EricYellow** [comment]
@banxi1988 could you update your CocoaPods project of vapor-sockets , please? I'd like to use it

**Comment by tanner0101** [comment]
I don't think this package would be usable on iOS even if you did get the Cocoapod working.

**Comment by banxi1988** [comment]
@EricYellow Hi, as @tanner0101  pointed out. we should better not use this project in iOS
See Also 
https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/NetworkingTopics/Articles/UsingSocketsandSocketStreams.html 

> Note: POSIX networking does not activate the cellular radio on iOS. For this reason, the POSIX networking API is generally discouraged in iOS.

finally , I copyed some code from this project into my project. 
that is ,I copyed the FoundationStream class and some needed dependency code.

**Pull request closed without merging**
